### ISSUE TITLE
llama7b-hf sorts numbers

### ISSUE THREAD

**Issue by lihuiliullh** [spcl/graph-of-thoughts#2]
I tried to use llama7b-hf to sort numbers according to the code in readme by changing chatGPT to llama7b-hf

lm = controller.Llama2HF(
    "graph_of_thoughts/controller/config.json", 
    model_name="llama7b-hf"
)

But I got the following results

WARNING:root:Could not parse step answer: Sure, I'd be happy to help you sort the list of numbers! Can you please provide the list of numbers for me to work with?. Returning empty list.

May I know whether this is a correct outcome?

**Comment by nblach** [comment]
Unfortunately, this is the expected outcome because Llama2 is not able to follow instructions as well as, for instance, GPT3.5 or GPT4. We were able to reproduce the issue and ensured that the prompt to model is correct, but as mentioned due to lacking capabilities, the LLM incorrectly asks for the input instead of producing a sorted list. For that reason the parser is unable to retrieve a list from the response and returns an empty list instead. On a side note, if you try to use the 70b model, it should work more smoothly.
